# Generated by Django 4.2.16 on 2024-09-26 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Store", "0008_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
