# Generated by Django 4.2.16 on 2024-10-15 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Store", "0009_alter_order_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
